---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by IGG.
--- DateTime: 2020/1/13 20:30
---
return {
    event = {
        data = {
            'value : object'
        },
        tag = {tag.Attr}
    },
    eventType = {
        data = {
            'value : object'
        },
        tag =  {tag.Attr}
    },
    eventTarget = {
        data = {
            'value : string',
        },
        tag = {tag.Attr}
    },
    eventTypeGroupStr = {
        data = {
            'value : string'
        },
        tag = {tag.Attr}
    },
    dates = {
        data = {
            'value : object'
        },
        tag =  {tag.Attr}
    },
    priority = {
        data = {
            'value : object'
        },
        tag =  {tag.Attr}
    },
    action = {
        data = {
            'value : object'
        },
        tag =  {tag.Attr}
    },
    name = {
        data = {
            'value : object'
        },
        tag = {tag.Attr}
    },
    parseAttr = {
        data = {
            'value : value'
        },
        tag = {tag.Attr}
    },
    generateCompName = {
        data = {
            'name : string',
            'Name : string'
        },
        tag = {tag.Attr}
    },
    component = {
        data = {
            'value : data'
        },
        tag = {tag.Attr}
    },

    handleTogether = {
        tag = {tag.Attr}
    },

    context = {
       data = {
            'data : value'
        },
        tag = {tag.Attr}
    },
}