---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by IGG.
--- DateTime: 2020/1/13 20:30
---
return {
    event = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    target = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    type = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    priority = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    action = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    className = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    primaryIndex = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    index = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    },
    muIndex = {
        data = {
            'value : object'
        },
        tag = tag.Attr
    }
}