---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018-11-27 23:18
---

Entitas = require("EcsCore")
require("GenerateEcsCore")
Matcher = Entitas.Matcher