---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018-12-02 1:38
---


require("Data.PositionVector3").init(10,10,5)
require("Data.PositionVector2")