---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018-12-01 22:36
---

---@class PosV2
---@field x int
---@field y int
local M = {}
local mt = {
    __eq = function(left, right)
        print("i am call")
        if left.x == right.x and left.y == right.y then
            return true
        end
        return false
    end,
    __tostring = function(t)
        return "{x:"..tostring(t.x).."," .."y"..":"..tostring(t.y).."}"
    end
}
local Cache = {}
---@private
function M.init(width, height)
    for x = 1, width do
        local xTable = {}
        for y = 1, height do
            xTable[y] = y
        end
        Cache[x] = xTable
    end
end

---@private
function M.new(x, y, z)
    if Cache[x] == nil then
        Cache[x] = {}
    end
    if Cache[x][y] == nil then
        Cache[x][y] = setmetatable({x = x,y = y}, mt)
    end
    return Cache[x][y]
    end

PosV2 = M.new
return M